# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "9f81198da99b79e14d70ca2c3cc1bbe44c6e69b6"

[[constraint]]
  name = "github.com/gorilla/websocket"
  revision = "5ed622c449da6d44c3c8329331ff47a9e5844f71"

[[constraint]]
  name = "github.com/juju/errors"
  revision = "c7d06af17c68cd34c835053720b21f6549d9b0ee"

[prune]
  go-tests = true
  unused-packages = true
