// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package kafka

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageKey struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Pair                 string   `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageKey) Reset()         { *m = MessageKey{} }
func (m *MessageKey) String() string { return proto.CompactTextString(m) }
func (*MessageKey) ProtoMessage()    {}
func (*MessageKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *MessageKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageKey.Unmarshal(m, b)
}
func (m *MessageKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageKey.Marshal(b, m, deterministic)
}
func (m *MessageKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageKey.Merge(m, src)
}
func (m *MessageKey) XXX_Size() int {
	return xxx_messageInfo_MessageKey.Size(m)
}
func (m *MessageKey) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageKey.DiscardUnknown(m)
}

var xxx_messageInfo_MessageKey proto.InternalMessageInfo

func (m *MessageKey) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *MessageKey) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

type MessageValue struct {
	Price                float32              `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
	Amount               float32              `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MessageValue) Reset()         { *m = MessageValue{} }
func (m *MessageValue) String() string { return proto.CompactTextString(m) }
func (*MessageValue) ProtoMessage()    {}
func (*MessageValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *MessageValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageValue.Unmarshal(m, b)
}
func (m *MessageValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageValue.Marshal(b, m, deterministic)
}
func (m *MessageValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageValue.Merge(m, src)
}
func (m *MessageValue) XXX_Size() int {
	return xxx_messageInfo_MessageValue.Size(m)
}
func (m *MessageValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageValue.DiscardUnknown(m)
}

var xxx_messageInfo_MessageValue proto.InternalMessageInfo

func (m *MessageValue) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *MessageValue) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *MessageValue) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageKey)(nil), "kafka.MessageKey")
	proto.RegisterType((*MessageValue)(nil), "kafka.MessageValue")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0x4e, 0x4c, 0xcb, 0x4e,
	0x94, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x0b, 0x26, 0x95, 0xa6, 0xe9, 0x97,
	0x64, 0x02, 0xd5, 0x95, 0x24, 0xe6, 0x16, 0x40, 0xd4, 0x29, 0xd9, 0x70, 0x71, 0xf9, 0x42, 0x34,
	0x7a, 0xa7, 0x56, 0x0a, 0x49, 0x71, 0x71, 0xa4, 0x56, 0x24, 0x67, 0x24, 0xe6, 0xa5, 0xa7, 0x4a,
	0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xf9, 0x42, 0x42, 0x5c, 0x2c, 0x05, 0x89, 0x99, 0x45,
	0x12, 0x4c, 0x60, 0x71, 0x30, 0x5b, 0xa9, 0x8c, 0x8b, 0x07, 0xaa, 0x3b, 0x2c, 0x31, 0xa7, 0x34,
	0x55, 0x48, 0x84, 0x8b, 0xb5, 0xa0, 0x28, 0x33, 0x19, 0xa2, 0x99, 0x29, 0x08, 0xc2, 0x11, 0x12,
	0xe3, 0x62, 0x4b, 0xcc, 0xcd, 0x2f, 0xcd, 0x2b, 0x01, 0xeb, 0x65, 0x0a, 0x82, 0xf2, 0x84, 0x2c,
	0xb8, 0x38, 0xe1, 0xce, 0x91, 0x60, 0x06, 0x4a, 0x71, 0x1b, 0x49, 0xe9, 0x41, 0x1c, 0xac, 0x07,
	0x73, 0xb0, 0x5e, 0x08, 0x4c, 0x45, 0x10, 0x42, 0x71, 0x12, 0x1b, 0x58, 0xda, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xe1, 0x60, 0x60, 0x6a, 0xf5, 0x00, 0x00, 0x00,
}
